### ISSUE TITLE
There is a circular dependency between XMPPFramework/Categories and XMPPFramework/Core

### ISSUE THREAD

**Issue by jayjayesh** [EugeneNguyen/XBChatModule#1]
hi EugeneNguyen,

pod "XBChatModule" causes folowing error
There is a circular dependency between XMPPFramework/Categories and XMPPFramework/Core

can u give hint to solve this....

**Comment by EugeneNguyen** [comment]
Hi Jay. this is a problem of XMPPFramework pod (which is reported here https://github.com/CocoaPods/Specs/issues/12819). in my case, i downgrade my pod version to 0.34.4 and the problem will be solved.

**Comment by jayjayesh** [comment]
thanks  EugeneNguyen ,   its working.....

**Comment by jayjayesh** [comment]
hi Eugene

i think there is missing How test your demo_project on two device in
README.md
https://github.com/EugeneNguyen/XBChatModule/blob/master/README.md .
can you provide me, step-by-step how to test on device?

And

i have another query is this library supports 'group chat'?

On Fri, Feb 13, 2015 at 7:38 PM, Eugene Nguyen notifications@github.com
wrote:

> Hi Jay. this is a problem of XMPPFramework pod (which is reported here
> CocoaPods/Specs#12819 https://github.com/CocoaPods/Specs/issues/12819).
> in my case, i downgrade my pod version to 0.34.4 and the problem will be
> solved.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EugeneNguyen/XBChatModule/issues/1#issuecomment-74258197
> .

## 

Regards :
Jayesh Lathiya
